// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {llm} from '../models';

export function ExportPrompt(arg1:string):Promise<domain.PromptInfo>;

export function GetProgress():Promise<domain.TranslateProgress>;

export function GetRunDetail(arg1:string):Promise<Record<string, any>>;

export function ImportPrompt(arg1:string,arg2:string):Promise<domain.SaveResult>;

export function ListModels():Promise<Array<llm.ModelInfo>>;

export function ListPrompts():Promise<Array<domain.PromptInfo>>;

export function ListRuns(arg1:string):Promise<Array<domain.RunInfo>>;

export function LoadAIConfig():Promise<llm.AIConfig>;

export function OpenInFolder(arg1:string):Promise<void>;

export function ReadFile(arg1:string,arg2:string):Promise<string>;

export function ResetPrompt(arg1:string):Promise<domain.SaveResult>;

export function SaveAIConfig(arg1:llm.AIConfig):Promise<domain.SaveResult>;

export function SelectDirectory():Promise<string>;

export function StartTranslate(arg1:string):Promise<domain.TranslateResult>;

export function TestLLMConnection(arg1:llm.AIConfig):Promise<domain.TestResult>;
