// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportPrompt(arg1:string):Promise<main.PromptInfo>;

export function GetProgress():Promise<main.TranslateProgress>;

export function GetRunDetail(arg1:string):Promise<Record<string, any>>;

export function ImportPrompt(arg1:string,arg2:string):Promise<main.SaveResult>;

export function ListModels():Promise<Array<main.ModelInfo>>;

export function ListPrompts():Promise<Array<main.PromptInfo>>;

export function ListRuns(arg1:string):Promise<Array<main.RunInfo>>;

export function LoadAIConfig():Promise<main.AIConfig>;

export function OpenInFolder(arg1:string):Promise<void>;

export function ReadFile(arg1:string,arg2:string):Promise<string>;

export function ResetPrompt(arg1:string):Promise<main.SaveResult>;

export function SaveAIConfig(arg1:main.AIConfig):Promise<main.SaveResult>;

export function SelectDirectory():Promise<string>;

export function StartTranslate(arg1:string):Promise<main.TranslateResult>;

export function TestLLMConnection(arg1:main.AIConfig):Promise<main.TestResult>;
