// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportPrompt(arg1) {
  return window['go']['main']['App']['ExportPrompt'](arg1);
}

export function GetProgress() {
  return window['go']['main']['App']['GetProgress']();
}

export function GetRunDetail(arg1) {
  return window['go']['main']['App']['GetRunDetail'](arg1);
}

export function ImportPrompt(arg1, arg2) {
  return window['go']['main']['App']['ImportPrompt'](arg1, arg2);
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function ListPrompts() {
  return window['go']['main']['App']['ListPrompts']();
}

export function ListRuns(arg1) {
  return window['go']['main']['App']['ListRuns'](arg1);
}

export function LoadAIConfig() {
  return window['go']['main']['App']['LoadAIConfig']();
}

export function OpenInFolder(arg1) {
  return window['go']['main']['App']['OpenInFolder'](arg1);
}

export function ReadFile(arg1, arg2) {
  return window['go']['main']['App']['ReadFile'](arg1, arg2);
}

export function ResetPrompt(arg1) {
  return window['go']['main']['App']['ResetPrompt'](arg1);
}

export function SaveAIConfig(arg1) {
  return window['go']['main']['App']['SaveAIConfig'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartTranslate(arg1) {
  return window['go']['main']['App']['StartTranslate'](arg1);
}

export function TestLLMConnection(arg1) {
  return window['go']['main']['App']['TestLLMConnection'](arg1);
}
